format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$shell\
$php\
$python\
$character"""

command_timeout = 5000

[username]
format = "[$user]($style)"
style_user = "black"

[hostname]
format = "[@$hostname]($style) "
style = "black"

[directory]
truncation_length = 5
truncate_to_repo = false
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_commit]
format = '[\($hash\)]($style)[$tag](yellow) '
style = "black"
tag_symbol = "  "
tag_disabled = false
tag_max_candidates = 2

[git_branch]
format = "[$branch(:$remote_branch)]($style)"
style = "bright-black"
only_attached = true

[git_status]
format = "[[(*$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)[$conflicted](yellow)"
style = "cyan"
conflicted = "resolving"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "​"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[php]
format = "[ $version](147) "

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[shell]
format = "[$indicator]($style)"
bash_indicator = "bash"
zsh_indicator = ""
style = "black italic"
disabled = false
